// AUTO-GENERATED by openapi-typescript — DO NOT EDIT (see docs/api/codegen.md)
// 真相源 = sim 端 pydantic 模型；改协议请改模型后 `npm run gen:protocol`，勿手写本文件。
export type paths = {
  readonly '/api/anchors': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /** 玩家档列表（不回传原始 tick/seq/seed） */
    readonly get: operations['listAnchors'];
    readonly put?: never;
    /** 新建游标（在当前会话点分叉标记） */
    readonly post: operations['createAnchor'];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/anchors/{id}': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    readonly post?: never;
    /** 删除游标（不动世界档，C6） */
    readonly delete: operations['deleteAnchor'];
    readonly options?: never;
    readonly head?: never;
    /** 重命名 */
    readonly patch: operations['renameAnchor'];
    readonly trace?: never;
  };
  readonly '/api/health': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /** 存活探针（戏外 meta shell） */
    readonly get: operations['getHealth'];
    readonly put?: never;
    readonly post?: never;
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/settings/profiles': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    /** LLM Profile 列表（api_key 仅掩码） */
    readonly get: operations['listProfiles'];
    readonly put?: never;
    /** 新建 Profile（api_key 提交即加密落库；响应永不回传明文） */
    readonly post: operations['createProfile'];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
  readonly '/api/settings/profiles/{id}': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    /** Profile 详情（api_key 掩码） */
    readonly get: operations['getProfile'];
    readonly put?: never;
    readonly post?: never;
    /** 删除 Profile */
    readonly delete: operations['deleteProfile'];
    readonly options?: never;
    readonly head?: never;
    /** 更新（api_key 可选，缺省保留） */
    readonly patch: operations['updateProfile'];
    readonly trace?: never;
  };
  readonly '/api/settings/profiles/{id}/activate': {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    readonly get?: never;
    readonly put?: never;
    /** 设为活动 Profile（单 profile 手动切换） */
    readonly post: operations['activateProfile'];
    readonly delete?: never;
    readonly options?: never;
    readonly head?: never;
    readonly patch?: never;
    readonly trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    readonly Actor: {
      readonly anim: string;
      readonly facing: components['schemas']['Facing'];
      readonly rtoken: components['schemas']['RToken'];
      readonly sprite: string;
      readonly tint?: number;
      readonly x: number;
      readonly y: number;
    };
    readonly ActorDelta: {
      readonly anim?: string;
      readonly facing?: components['schemas']['Facing'];
      /** @enum {string} */
      readonly op?: 'add' | 'remove';
      readonly rtoken: components['schemas']['RToken'];
      readonly sprite?: string;
      readonly tint?: number;
      readonly x?: number;
      readonly y?: number;
    };
    readonly AnchorCreate: {
      readonly name: string;
    };
    readonly AnchorListItem: {
      /** Format: date-time */
      readonly created_at: string;
      readonly id: string;
      readonly name: string;
      readonly protected: boolean;
      /** @description 叙事化时间标签，非 tick 数值 */
      readonly story_label: string;
    };
    readonly AnchorRename: {
      readonly name: string;
    };
    readonly CombatEventMessage: {
      /** @enum {string} */
      readonly channel: 'render';
      /** @description 本战斗内序，非世界 tick */
      readonly exchange: number;
      readonly exchange_resolved: boolean;
      readonly hits?: readonly components['schemas']['Hit'][];
      readonly posture_visual: string;
      readonly projectiles?: readonly components['schemas']['Projectile'][];
      readonly rtoken: components['schemas']['RToken'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'combat_event';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly CombatInfo: {
      readonly active: boolean;
    };
    readonly ControlAckMessage: {
      /** @enum {string} */
      readonly action: 'pause' | 'resume' | 'set_speed';
      readonly applied: boolean;
      /** @enum {string} */
      readonly channel: 'control';
      /** @enum {integer} */
      readonly speed?: 1 | 4 | 16;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'control_ack';
      readonly v: string;
      readonly ws_seq: number;
    };
    /** @enum {string} */
    readonly Facing: 'n' | 'e' | 's' | 'w';
    readonly FullSnapshotMessage: {
      readonly actors: readonly components['schemas']['Actor'][];
      /** @enum {string} */
      readonly channel: 'render';
      readonly combat?: components['schemas']['CombatInfo'] | null;
      readonly lights: readonly components['schemas']['Light'][];
      readonly map: components['schemas']['MapInfo'];
      readonly structures: readonly components['schemas']['Structure'][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'full_snapshot';
      readonly v: string;
      readonly weather: components['schemas']['Weather'];
      readonly ws_seq: number;
    };
    readonly HealthStatus: {
      /** @description 戏外只读，不回流戏内 */
      readonly in_combat: boolean;
      /** @enum {string} */
      readonly status: 'ok';
      readonly world_running: boolean;
    };
    readonly Hit: {
      /** @enum {string} */
      readonly bleed: 'none' | 'light' | 'heavy';
      readonly rtoken: components['schemas']['RToken'];
      readonly visual: string;
    };
    readonly ImpulseFeedbackMessage: {
      /** @enum {string} */
      readonly channel: 'control';
      /** @enum {string} */
      readonly cue: 'accepted' | 'hesitation' | 'complaint' | 'resistance';
      readonly delay_ms: number;
      readonly injected: boolean;
      readonly reaction_monologue: components['schemas']['MonologueReaction'];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'impulse_feedback';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly Light: {
      readonly flicker: number;
      readonly kind: string;
      readonly radius: number;
      readonly rtoken: components['schemas']['RToken'];
      readonly x: number;
      readonly y: number;
    };
    readonly LightDelta: {
      readonly flicker?: number;
      readonly rtoken: components['schemas']['RToken'];
    };
    readonly LlmParams: {
      readonly max_tokens?: number;
      readonly temperature?: number;
    };
    readonly LoadAnchorMessage: {
      readonly anchor_id: string;
      /** @enum {string} */
      readonly channel: 'session';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'load_anchor';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly MapInfo: {
      readonly h: number;
      readonly tileset: string;
      readonly w: number;
    };
    readonly MonologueMessage: {
      readonly anchor_ref?: string | null;
      /** @enum {string} */
      readonly channel: 'narrative';
      readonly content: string;
      /** @enum {string} */
      readonly form: 'bubble' | 'thought' | 'plan';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'monologue';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly MonologueReaction: {
      readonly content: string;
      /** @enum {string} */
      readonly form: 'bubble' | 'thought' | 'plan';
    };
    /** @description 玩家点击寻路：客户端只发目标格坐标，sim 负责寻路并驱动主角；无 rtoken（服务端知道主角是谁） */
    readonly MoveRequestMessage: {
      /** @enum {string} */
      readonly channel: 'render';
      /** @description 目标格 X（整数格坐标） */
      readonly target_x: number;
      /** @description 目标格 Y（整数格坐标） */
      readonly target_y: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'move_request';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly PerceptionMessage: {
      /** @enum {string} */
      readonly channel: 'narrative';
      /** @description 第一人称叙事，无数值无系统词 */
      readonly content: string;
      readonly form?: ('bubble' | 'thought' | 'plan') | null;
      /** @enum {string} */
      readonly sense: 'sight' | 'sound' | 'smell' | 'touch' | 'interoception';
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'perception';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly PlayerImpulseMessage: {
      /** @enum {string} */
      readonly channel: 'control';
      readonly preset?: string | null;
      /** @description 玩家原始直觉输入；sim 负责叙事化 */
      readonly text: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'player_impulse';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly ProblemDetail: {
      readonly detail?: string;
      readonly status: number;
      readonly title: string;
      readonly type?: string;
    };
    readonly ProfileCreate: {
      /** @description 明文入，后端即加密；响应永不回传 */
      readonly api_key: string;
      readonly base_url: string;
      readonly model: string;
      readonly name: string;
      readonly params: components['schemas']['LlmParams'];
      /** @enum {string} */
      readonly provider: 'openai' | 'deepseek' | 'qwen' | 'ollama' | 'lmstudio';
    };
    readonly ProfileListItem: {
      readonly active: boolean;
      /** @description 仅掩码，前端无法据此调用 LLM */
      readonly api_key_hint: string;
      readonly base_url: string;
      readonly id: string;
      readonly model: string;
      readonly name: string;
      readonly params: components['schemas']['LlmParams'];
      /** @enum {string} */
      readonly provider: 'openai' | 'deepseek' | 'qwen' | 'ollama' | 'lmstudio';
    };
    readonly ProfileUpdate: {
      /** @description 可选，省略即保留原密钥 */
      readonly api_key?: string;
      readonly base_url?: string;
      readonly model?: string;
      readonly name?: string;
      readonly params?: components['schemas']['LlmParams'];
      /** @enum {string} */
      readonly provider?: 'openai' | 'deepseek' | 'qwen' | 'ollama' | 'lmstudio';
    };
    readonly Projectile: {
      readonly dur: number;
      readonly kind: string;
      readonly rtoken: components['schemas']['RToken'];
      readonly x0: number;
      readonly x1: number;
      readonly y0: number;
      readonly y1: number;
    };
    /** @description 不透明渲染替身：仅用于精灵跟踪，与内部 entity_id 解耦、不可反查游戏状态、连接生命周期内有效（ws-protocol.md §5） */
    readonly RToken: string;
    readonly SetControlMessage: {
      /** @enum {string} */
      readonly action: 'pause' | 'resume' | 'set_speed';
      /** @enum {string} */
      readonly channel: 'control';
      /** @enum {integer} */
      readonly speed?: 1 | 4 | 16;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'set_control';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly StateDeltaMessage: {
      readonly actors: readonly components['schemas']['ActorDelta'][];
      /** @enum {string} */
      readonly channel: 'render';
      readonly lights?: readonly components['schemas']['LightDelta'][];
      readonly structures?: readonly components['schemas']['StructureDelta'][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'state_delta';
      readonly v: string;
      readonly weather?: components['schemas']['Weather'];
      readonly ws_seq: number;
    };
    readonly Structure: {
      /** @enum {string} */
      readonly phase: 'built' | 'collapsing' | 'rubble';
      readonly rtoken: components['schemas']['RToken'];
      readonly tileset_ref: string;
      readonly x: number;
      readonly y: number;
    };
    readonly StructureDelta: {
      /** @enum {string} */
      readonly op?: 'add' | 'remove';
      /** @enum {string} */
      readonly phase?: 'built' | 'collapsing' | 'rubble';
      readonly rtoken: components['schemas']['RToken'];
      readonly tileset_ref?: string;
      readonly x?: number;
      readonly y?: number;
    };
    readonly SyncRequestMessage: {
      /** @enum {string} */
      readonly channel: 'session';
      readonly reason: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'sync_request';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly TimescaleMessage: {
      readonly active: boolean;
      /** @enum {string} */
      readonly channel: 'control';
      /** @enum {string} */
      readonly mode: 'normal' | 'combat';
      readonly note?: string | null;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'timescale';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly Weather: {
      readonly ambient_light: number;
      readonly visual: string;
    };
    /** @description 通用信封；具体消息见各 *Message schema 的 oneOf WsMessage */
    readonly WsEnvelope: {
      /** @enum {string} */
      readonly channel: 'render' | 'narrative' | 'control' | 'session' | 'error';
      readonly data: unknown;
      readonly type: string;
      /** @description 协商后的协议版本 major.minor */
      readonly v: string;
      /** @description 传输序号，非世界 tick */
      readonly ws_seq: number;
    };
    readonly WsErrorMessage: {
      /** @enum {string} */
      readonly channel: 'error';
      readonly code: string;
      /** @description 戏内文风，不向玩家显示系统措辞 */
      readonly message: string;
      readonly ref: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      readonly type: 'error';
      readonly v: string;
      readonly ws_seq: number;
    };
    readonly WsMessage:
      | components['schemas']['PlayerImpulseMessage']
      | components['schemas']['SetControlMessage']
      | components['schemas']['LoadAnchorMessage']
      | components['schemas']['MoveRequestMessage']
      | components['schemas']['SyncRequestMessage']
      | components['schemas']['FullSnapshotMessage']
      | components['schemas']['StateDeltaMessage']
      | components['schemas']['PerceptionMessage']
      | components['schemas']['MonologueMessage']
      | components['schemas']['ImpulseFeedbackMessage']
      | components['schemas']['CombatEventMessage']
      | components['schemas']['TimescaleMessage']
      | components['schemas']['ControlAckMessage']
      | components['schemas']['WsErrorMessage'];
  };
  responses: {
    /** @description RFC 7807 问题详情（戏外工程措辞，不回灌 Agent） */
    readonly Problem: {
      headers: {
        readonly [name: string]: unknown;
      };
      content: {
        readonly 'application/json': components['schemas']['ProblemDetail'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  readonly listAnchors: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description anchors */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': readonly components['schemas']['AnchorListItem'][];
        };
      };
    };
  };
  readonly createAnchor: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['AnchorCreate'];
      };
    };
    readonly responses: {
      /** @description created */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': components['schemas']['AnchorListItem'];
        };
      };
    };
  };
  readonly deleteAnchor: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description deleted */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 404: components['responses']['Problem'];
      readonly 409: components['responses']['Problem'];
    };
  };
  readonly renameAnchor: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['AnchorRename'];
      };
    };
    readonly responses: {
      /** @description renamed */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': components['schemas']['AnchorListItem'];
        };
      };
      readonly 404: components['responses']['Problem'];
    };
  };
  readonly getHealth: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description ok */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
  readonly listProfiles: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description profiles */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': readonly components['schemas']['ProfileListItem'][];
        };
      };
    };
  };
  readonly createProfile: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path?: never;
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['ProfileCreate'];
      };
    };
    readonly responses: {
      /** @description created */
      readonly 201: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': components['schemas']['ProfileListItem'];
        };
      };
    };
  };
  readonly getProfile: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description profile */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': components['schemas']['ProfileListItem'];
        };
      };
      readonly 404: components['responses']['Problem'];
    };
  };
  readonly deleteProfile: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description deleted */
      readonly 204: {
        headers: {
          readonly [name: string]: unknown;
        };
        content?: never;
      };
      readonly 404: components['responses']['Problem'];
    };
  };
  readonly updateProfile: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody: {
      readonly content: {
        readonly 'application/json': components['schemas']['ProfileUpdate'];
      };
    };
    readonly responses: {
      /** @description updated */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': components['schemas']['ProfileListItem'];
        };
      };
      readonly 404: components['responses']['Problem'];
    };
  };
  readonly activateProfile: {
    readonly parameters: {
      readonly query?: never;
      readonly header?: never;
      readonly path: {
        readonly id: string;
      };
      readonly cookie?: never;
    };
    readonly requestBody?: never;
    readonly responses: {
      /** @description activated */
      readonly 200: {
        headers: {
          readonly [name: string]: unknown;
        };
        content: {
          readonly 'application/json': components['schemas']['ProfileListItem'];
        };
      };
      readonly 404: components['responses']['Problem'];
    };
  };
}
