/**
 * tools/gen-protocol.ts — OpenAPI → shared/protocol.ts 生成脚本
 *
 * 能力域：接口/兼容性（kilo TASK-002）。对齐 docs/api/codegen.md。
 *
 * 做什么：
 *   1. 取 OpenAPI 源（默认 mock：shared/openapi.json；sim 起服务后用 --src <url> 拉真实 /api/openapi.json）
 *   2. openapi-typescript 生成 TS（--immutable --export-type --alphabetize）
 *   3. 注入 AUTO-GENERATED banner（CI 手写禁令锚点）
 *   4. prettier 格式化（沿用 client/.prettierrc.json 风格）
 *   5. 写 shared/protocol.ts
 *   --check 模式：生成到临时文件，与已提交的 shared/protocol.ts 比对，漂移则非零退出（CI 守卫）。
 *
 * 运行（在 client/ 下，复用其 node_modules）：
 *   npm run gen:protocol          # 生成
 *   npm run gen:protocol:check    # CI 漂移检测
 *   node tools/gen-protocol.ts --src http://127.0.0.1:8000/api/openapi.json   # 切真实源
 *
 * 仅用 node 内置模块（CJS 风格，靠 Node 24 类型擦除运行），不 import npm 包；
 * openapi-typescript / prettier 通过 client/node_modules/.bin 调用。
 */

const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const { spawnSync } = require("node:child_process");

const REPO_ROOT = path.resolve(__dirname, "..");
const BANNER =
  "// AUTO-GENERATED by openapi-typescript — DO NOT EDIT (see docs/api/codegen.md)\n" +
  "// 真相源 = sim 端 pydantic 模型；改协议请改模型后 `npm run gen:protocol`，勿手写本文件。\n";

function entry(moduleName, rel) {
  return path.join(REPO_ROOT, "client", "node_modules", moduleName, rel);
}

// openapi-typescript / prettier 的真实 JS 入口（用 node 直接执行，避免 shell:true + args 的 DEP0190 警告）
const ENTRIES = {
  oats: entry("openapi-typescript", path.join("bin", "cli.js")),
  prettier: entry("prettier", path.join("bin", "prettier.cjs")),
};

function ensureBins() {
  for (const [label, p] of Object.entries(ENTRIES)) {
    if (!fs.existsSync(p)) {
      console.error(
        `[gen-protocol] 找不到 ${label} 入口 ${p}：请先在 client/ 下执行 \`npm ci\`（依赖由 cline 锁定于 client/package.json）。`
      );
      process.exit(1);
    }
  }
}

function parseArgs(argv) {
  const out = { src: null, out: null, check: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--src") out.src = argv[++i];
    else if (a === "--out") out.out = argv[++i];
    else if (a === "--check") out.check = true;
    else if (a === "-h" || a === "--help") {
      console.log("usage: gen-protocol [--src <file|url>] [--out <path>] [--check]");
      process.exit(0);
    }
  }
  return out;
}

function run(entryPath, args, label) {
  const r = spawnSync(process.execPath, [entryPath, ...args], { encoding: "utf8" });
  if (r.error || r.status !== 0) {
    console.error(`[gen-protocol] ${label} 失败 (exit ${r.status})`);
    if (r.stderr) console.error(r.stderr);
    if (r.stdout) console.error(r.stdout);
    process.exit(1);
  }
  return r;
}

function generate(src) {
  const tmp = path.join(os.tmpdir(), `oats-${process.pid}-${Date.now()}.ts`);
  run(ENTRIES.oats, [src, "--immutable", "--export-type", "--alphabetize", "-o", tmp], "openapi-typescript");
  let body = fs.readFileSync(tmp, "utf8");
  // 去掉 BOM 与 openapi-typescript 自带的头注释块（避免与我们的 banner 重复）
  body = body.replace(/^\uFEFF/, "");
  body = body.replace(/^\/\*\*[\s\S]*?\*\/\s*/, (m) => (/auto-generated/i.test(m) ? "" : m));
  const withBanner = BANNER + body;
  const tmp2 = path.join(os.tmpdir(), `prettier-${process.pid}-${Date.now()}.ts`);
  fs.writeFileSync(tmp2, withBanner, "utf8");
  run(
    ENTRIES.prettier,
    ["--parser", "typescript", "--config", path.join(REPO_ROOT, "client", ".prettierrc.json"), "--write", tmp2],
    "prettier"
  );
  const final = fs.readFileSync(tmp2, "utf8");
  fs.unlinkSync(tmp);
  fs.unlinkSync(tmp2);
  return final;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const src = args.src || path.join(REPO_ROOT, "shared", "openapi.json");
  const outPath = args.out || path.join(REPO_ROOT, "shared", "protocol.ts");
  ensureBins();

  if (!src.startsWith("http")) {
    if (!fs.existsSync(src)) {
      console.error(`[gen-protocol] OpenAPI 源不存在: ${src}`);
      process.exit(1);
    }
  }

  const generated = generate(src);

  if (args.check) {
    if (!fs.existsSync(outPath)) {
      console.error(`[gen-protocol] --check：目标不存在 ${outPath}（请先运行 npm run gen:protocol 并提交）`);
      process.exit(1);
    }
    const committed = fs.readFileSync(outPath, "utf8");
    if (committed !== generated) {
      console.error("[gen-protocol] 漂移：生成物与提交的 shared/protocol.ts 不一致。");
      console.error("请运行 `npm run gen:protocol` 重新生成并提交（改协议须改 sim pydantic 模型，勿手写）。");
      process.exit(1);
    }
    console.log("[gen-protocol] --check 通过：生成物与提交一致。");
    return;
  }

  fs.writeFileSync(outPath, generated, "utf8");
  console.log(`[gen-protocol] 已生成 ${path.relative(REPO_ROOT, outPath)}（源: ${src.startsWith("http") ? src : path.relative(REPO_ROOT, src)}）`);
  if (!args.src) {
    console.log("[gen-protocol] 提示：当前为 mock 源（shared/openapi.json）。sim 起服务后用 --src http://127.0.0.1:8000/api/openapi.json 切真实，切换点见 docs/api/codegen.md。");
  }
}

main();
